#version: '3'
services:
  intellij-ce:
    build: ./docker/intellij-ce
    ports:
     - "3003:3000"
    networks:
     - "dev-net"
 #   volumes:
 #    - .:/code
  mse:
    build: ./docker/mse
    ports:
      - "3004:3000"
    networks:
     - "dev-net"      
  tiled:
    build: "./docker/tiled"
    ports:
      - "3005:3000"
    networks:
     - "dev-net"
networks:
    dev-net: